# **Multiple Linear Regression**

In [167]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [170]:
# Importing the dataset
dataset=pd.read_csv("/kaggle/input/airpressure/Folds5x2_pp.csv")
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:,-1].values 
print(dataset)

         AT      V       AP     RH      PE
0      8.34  40.77  1010.84  90.01  480.48
1     23.64  58.49  1011.40  74.20  445.75
2     29.74  56.90  1007.15  41.91  438.76
3     19.07  49.69  1007.22  76.79  453.09
4     11.80  40.66  1017.13  97.20  464.43
...     ...    ...      ...    ...     ...
9563  15.12  48.92  1011.80  72.93  462.59
9564  33.41  77.95  1010.30  59.72  432.90
9565  15.99  43.34  1014.20  78.66  465.96
9566  17.65  59.87  1018.58  94.65  450.93
9567  23.68  51.30  1011.86  71.24  451.67

[9568 rows x 5 columns]


In [171]:
#Check for missing values
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB
None


In [172]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [173]:
# Training the Multiple Linear Regression model on the Training set
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [174]:
# Predicting the Test set results
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[459.36 458.92]
 [433.94 430.55]
 [474.87 473.85]
 ...
 [445.7  442.69]
 [445.4  447.31]
 [434.67 429.42]]


In [175]:
# Predicting a paticular result
regressor.predict([[8.34, 40.77, 1010.84, 90.01]])

array([477.05])

In [176]:
# Evaluating the Model Performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.931485529163037

# **Polynomial Regression**

In [177]:
# Training the Polynomial Regression model on the Training set
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
x_poly = poly_reg.fit_transform(x_train)
regressor_2 = LinearRegression()
regressor_2.fit(x_poly, y_train)

LinearRegression()

In [178]:
# Predicting the Test set results
y_pred = regressor_2.predict(poly_reg.transform(x_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[459.05 458.92]
 [435.62 430.55]
 [474.37 473.85]
 ...
 [445.46 442.69]
 [443.85 447.31]
 [435.79 429.42]]


In [179]:
# Predicting a paticular result
regressor_2.predict(poly_reg.fit_transform([[8.34, 40.77, 1010.84, 90.01]]))

array([480.18])

In [180]:
# Evaluating the Model Performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9446120068088645